In [1]:
"""
1. Write a Python program that: 
a. Creates a numpy-array of integers of size NxMx3, with N and M chosen dynamically by the 
operator (using the input function) containing randomly generated numbers in the range [100, 
5000] 
b. Define a function that swaps even-numbered columns with odd-numbered columns and vice 
versa 
c. Define a function that exchanges even rows with odd rows and vice versa 
d. Given a random number X as input, all pixels with a value equal to X must be set to 0 
"""

'\n1. Write a Python program that: \na. Creates a numpy-array of integers of size NxMx3, with N and M chosen dynamically by the \noperator (using the input function) containing randomly generated numbers in the range [100, \n5000] \nb. Define a function that swaps even-numbered columns with odd-numbered columns and vice \nversa \nc. Define a function that exchanges even rows with odd rows and vice versa \nd. Given a random number X as input, all pixels with a value equal to X must be set to 0 \n'

In [1]:
import numpy as np
import random
import math as mt

In [3]:
# 1A

def arr_creation():
    N = int(input("Rows: "))
    M = int(input("Columns: "))
    arr = np.random.randint(100, 5001, size = (N, M, 3))
    return arr

In [4]:
I = arr_creation()
print(I)

Rows: 4
Columns: 4
[[[4245 2636 4335]
  [ 486 4316 3417]
  [1501  878 4276]
  [1839 2052  191]]

 [[2010 4822  473]
  [4691  345 4604]
  [2363 4728 2962]
  [4950 3385 2702]]

 [[1310 3893 2200]
  [3800 3825 3812]
  [1058 3345 1784]
  [1020  289 1806]]

 [[1978 2141 2329]
  [2214 4148 3010]
  [3286 4018 2393]
  [2812 3996 2009]]]


In [5]:
# 1B

def swap_columns(I):
    I2 = I.copy()
    for i in range(0, I.shape[0]):
        for j in range(0, I.shape[1], 2):
            I2[i,j] = I[i,j+1]
            I2[i,j+1] = I[i,j]
    return I2

print("Swap columns \n", swap_columns(I))

# 1C

def swap_rows(I):
    I2 = I.copy()
    for i in range(0, I.shape[0], 2):
        for j in range(0, I.shape[1]):
            I2[i,j] = I[i+1, j]
            I2[i+1,j] = I[i,j]
    return I2

print("\nSwap rows \n", swap_rows(I))

# 1D

def pixel_0(I):
    I2 = I.copy()
    X = int(input("Number between 100 and 5000: "))
    if X < 100 or X > 5000:
        raise ValueError
    for i in range(0, I.shape[0]):
        for j in range(0, I.shape[1]):
            for k in range(0, I.shape[2]):
                if I[i][j][k] == X:
                    I2[i][j][k] = 0
    return I2

print("\nCheck for 0 \n", pixel_0(I))

Swap columns 
 [[[ 486 4316 3417]
  [4245 2636 4335]
  [1839 2052  191]
  [1501  878 4276]]

 [[4691  345 4604]
  [2010 4822  473]
  [4950 3385 2702]
  [2363 4728 2962]]

 [[3800 3825 3812]
  [1310 3893 2200]
  [1020  289 1806]
  [1058 3345 1784]]

 [[2214 4148 3010]
  [1978 2141 2329]
  [2812 3996 2009]
  [3286 4018 2393]]]

Swap rows 
 [[[2010 4822  473]
  [4691  345 4604]
  [2363 4728 2962]
  [4950 3385 2702]]

 [[4245 2636 4335]
  [ 486 4316 3417]
  [1501  878 4276]
  [1839 2052  191]]

 [[1978 2141 2329]
  [2214 4148 3010]
  [3286 4018 2393]
  [2812 3996 2009]]

 [[1310 3893 2200]
  [3800 3825 3812]
  [1058 3345 1784]
  [1020  289 1806]]]
Number between 100 and 5000: 2000

Check for 0 
 [[[4245 2636 4335]
  [ 486 4316 3417]
  [1501  878 4276]
  [1839 2052  191]]

 [[2010 4822  473]
  [4691  345 4604]
  [2363 4728 2962]
  [4950 3385 2702]]

 [[1310 3893 2200]
  [3800 3825 3812]
  [1058 3345 1784]
  [1020  289 1806]]

 [[1978 2141 2329]
  [2214 4148 3010]
  [3286 4018 2393]
  [2812 

In [6]:
"""
2. Write a Python program that: 
a) Creates a numpy-array of integers of size NxNx3, with N chosen dynamically by the operator 
(using the input function) containing randomly generated numbers in the range [0, 255] 
b) Replaces the values of the main diagonal with the secondary diagonal. 
c) Set the secondary diagonal to zero 
d) Binarise the resulting matrix with respect to a threshold value S chosen by the operator. Thus, if 
I[x,y] < S , then I[x,y] = 0 otherwise I[x,y] = 255
"""

'\n2. Write a Python program that: \na) Creates a numpy-array of integers of size NxNx3, with N chosen dynamically by the operator \n(using the input function) containing randomly generated numbers in the range [0, 255] \nb) Replaces the values of the main diagonal with the secondary diagonal. \nc) Set the secondary diagonal to zero \nd) Binarise the resulting matrix with respect to a threshold value S chosen by the operator. Thus, if \nI[x,y] < S , then I[x,y] = 0 otherwise I[x,y] = 255\n'

In [3]:
# 2A

def arr_creation2():
    N = int(input("Rows: "))
    M = int(input("Columns: "))
    arr = np.random.randint(0, 256, size = (N, M, 3))
    return arr

In [8]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[123 169 224]
  [254  23 201]
  [207  62   6]
  [ 95 196 210]]

 [[150 206  70]
  [141 234  33]
  [ 65  63 135]
  [137  34 199]]

 [[184 216 248]
  [152 218 100]
  [  5  13 109]
  [101 190  95]]

 [[123  64 156]
  [115  83  95]
  [ 83 103 224]
  [150 132 128]]]


In [9]:
# 2B

def main_to_sec(I):
    I2 = I.copy()
    for i in range(I.shape[0]):
        for j in range(I.shape[1]):
            if i == j: # Main diagonal element
                I2[i, j] = I[i, I.shape[0] - 1 - i] # Secondary diagonal element
                I2[i, I.shape[0] - 1 - i] = I[i, j]
    return I2

print("Exchange of diagonals \n", main_to_sec(I))

# 2C

def sec_to_zero(I):
    I2 = I.copy()
    for i in range(I.shape[0]):
        for j in range(I.shape[1]):
            if j == I.shape[0] - 1 - i:
                I2[i, j] = 0
    return I2

print("\nSecondary diagonal to 0 \n", sec_to_zero(I))

# 2D

def binarization(I):
    I2 = I.copy()
    S = int(input("Threshold: "))
    if S < 0 or S > 255:
        raise ValueError
    I2[I <= S] = 0
    I2[I > S] = 255
    return I2

print("\nBinarization \n", binarization(I))

Exchange of diagonals 
 [[[ 95 196 210]
  [254  23 201]
  [207  62   6]
  [123 169 224]]

 [[150 206  70]
  [ 65  63 135]
  [141 234  33]
  [137  34 199]]

 [[184 216 248]
  [  5  13 109]
  [152 218 100]
  [101 190  95]]

 [[150 132 128]
  [115  83  95]
  [ 83 103 224]
  [123  64 156]]]

Secondary diagonal to 0 
 [[[123 169 224]
  [254  23 201]
  [207  62   6]
  [  0   0   0]]

 [[150 206  70]
  [141 234  33]
  [  0   0   0]
  [137  34 199]]

 [[184 216 248]
  [  0   0   0]
  [  5  13 109]
  [101 190  95]]

 [[  0   0   0]
  [115  83  95]
  [ 83 103 224]
  [150 132 128]]]
Threshold: 100

Binarization 
 [[[255 255 255]
  [255   0 255]
  [255   0   0]
  [  0 255 255]]

 [[255 255   0]
  [255 255   0]
  [  0   0 255]
  [255   0 255]]

 [[255 255 255]
  [255 255   0]
  [  0   0 255]
  [255 255   0]]

 [[255   0 255]
  [255   0   0]
  [  0 255 255]
  [255 255 255]]]


In [10]:
"""
3. Write a Python program that: 
1. Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator 
(using the input function) containing randomly generated numbers in the range [0, 255] 
2. Given as input the x,y coordinate points and the values of width w and height h, extract the patch 
of position I[x:x+w, y:y+w]. Perform this operation on all 3 channels, obtaining 3 different sub
matrices: M1, M2, M3 
3. From point b, set the areas represented by M1, M2, M3 to zero in the initial matrix.
"""

'\n3. Write a Python program that: \n1. Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator \n(using the input function) containing randomly generated numbers in the range [0, 255] \n2. Given as input the x,y coordinate points and the values of width w and height h, extract the patch \nof position I[x:x+w, y:y+w]. Perform this operation on all 3 channels, obtaining 3 different sub\nmatrices: M1, M2, M3 \n3. From point b, set the areas represented by M1, M2, M3 to zero in the initial matrix.\n'

In [2]:
# 3A

def arr_creation2():
    N = int(input("Rows: "))
    M = int(input("Columns: "))
    arr = np.random.randint(0, 256, size = (N, M, 3))
    return arr

In [12]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[ 39 154  66]
  [124 148  91]
  [174 212 143]
  [199 252 138]]

 [[ 18 194  27]
  [123 100  58]
  [151 121 237]
  [ 72 232   4]]

 [[ 37 195  97]
  [243  55 200]
  [ 72 228 226]
  [175  33 152]]

 [[ 72  44  92]
  [ 15  99 177]
  [ 77  24  18]
  [206 237 193]]]


In [13]:
# 3B

def patch_extraction(I):
    x = int(input("x coordinate: "))
    y = int(input("y coordinate: "))
    h = int(input("x extension aka height: "))
    w = int(input("y extension aka width: "))
    if x < 0 or y < 0 or x + h > I.shape[0] or y + w > I.shape[1]:
        raise ValueError
    M1 = I[x:x+h, y:y+w, 0]
    M2 = I[x:x+h, y:y+w, 1]
    M3 = I[x:x+h, y:y+w, 2]
    return (M1, M2, M3)

print("Patch extraction \n", patch_extraction(I))

x coordinate: 1
y coordinate: 1
x extension aka height: 2
y extension aka width: 2
Patch extraction 
 (array([[123, 151],
       [243,  72]]), array([[100, 121],
       [ 55, 228]]), array([[ 58, 237],
       [200, 226]]))


In [14]:
# 3C

I2 = I.copy()
x = int(input("x coordinate: "))
y = int(input("y coordinate: "))
h = int(input("x extension aka height: "))
w = int(input("y extension aka width: "))
I2[x:x+h, y:y+w, 0] = 0
I2[x:x+h, y:y+w, 1] = 0
I2[x:x+h, y:y+w, 2] = 0
print("\nPatch to 0 \n", I2)

x coordinate: 1
y coordinate: 1
x extension aka height: 2
y extension aka width: 2

Patch to 0 
 [[[ 39 154  66]
  [124 148  91]
  [174 212 143]
  [199 252 138]]

 [[ 18 194  27]
  [  0   0   0]
  [  0   0   0]
  [ 72 232   4]]

 [[ 37 195  97]
  [  0   0   0]
  [  0   0   0]
  [175  33 152]]

 [[ 72  44  92]
  [ 15  99 177]
  [ 77  24  18]
  [206 237 193]]]


In [15]:
"""
4.Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator (using 
the input function) containing randomly generated numbers in the range [0, 255] 
a. Consider the following pattern of neighbouring pixels:: [...]
b. Each pixel of both even co-ordinates and odd channel will be replaced by the average of 
the neighbours 
c. Each pixel of both odd co-ordinates and all other channels will be replaced by the 
absolute value of the difference of the neighbours
"""

'\n4.Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator (using \nthe input function) containing randomly generated numbers in the range [0, 255] \na. Consider the following pattern of neighbouring pixels:: [...]\nb. Each pixel of both even co-ordinates and odd channel will be replaced by the average of \nthe neighbours \nc. Each pixel of both odd co-ordinates and all other channels will be replaced by the \nabsolute value of the difference of the neighbours\n'

In [2]:
# 4A

def arr_creation2():
    N = int(input("Rows: "))
    M = int(input("Columns: "))
    arr = np.random.randint(0, 256, size = (N, M, 3))
    return arr

I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[116 183 243]
  [ 25  75   2]
  [149  69  70]
  [212 141  56]]

 [[ 93 134 201]
  [173  21  12]
  [ 14 151 199]
  [ 77 107  60]]

 [[106 196 109]
  [ 45 252  46]
  [ 51   0  84]
  [ 97 210  12]]

 [[169 160  77]
  [ 11  81   0]
  [118  31 112]
  [ 13  71  22]]]


In [17]:
# 4B + 4C

def odd_coor(I):
    I2 = I.copy()
    for i in range(I.shape[0]):
        for j in range(I.shape[1]):
            for k in range(I.shape[2]):
                if i % 2 == 0 and j % 2 == 0 and k % 2 != 0:
                    neighbors = []
                    if i > 0: # Sopra
                        neighbors.append(I[i-1][j][k])
                    if i < I.shape[0] - 1: # Sotto
                        neighbors.append(I[i+1][j][k])
                    if j > 0: # Sinistra
                        neighbors.append(I[i][j-1][k])
                    if j < I.shape[1] - 1: # Destra
                        neighbors.append(I[i][j+1][k])
                    if neighbors:
                        I2[i][j][k] = sum(neighbors) / len(neighbors) # Media
                        
                elif i % 2 != 0 and j % 2 != 0 and k % 2 == 0:
                    neighbors = []
                    if i > 0: # Sopra
                        neighbors.append(I[i-1][j][k])
                    if i < I.shape[0] - 1: # Sotto
                        neighbors.append(I[i+1][j][k])
                    if j > 0: # Sinistra
                        neighbors.append(I[i][j-1][k])
                    if j < I.shape[1] - 1: # Destra
                        neighbors.append(I[i][j+1][k])
                    if neighbors:
                        I2[i][j][k] = abs(neighbors[0] - neighbors[1]) # Differenza in valore assoluto
    return I2

I2 = odd_coor(I)
print(I2)

[[[137 173 203]
  [ 51 136 176]
  [247 146 229]
  [193 143 222]]

 [[ 10 210  38]
  [  5 177  87]
  [254 159  59]
  [162 102 103]]

 [[137 215  35]
  [ 46 217  89]
  [ 45 155  10]
  [ 31 203 119]]

 [[ 55 219   7]
  [  9 139  82]
  [188  44  81]
  [157  87  38]]]


In [18]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[153  56 138]
  [206  73  61]
  [162 167 134]
  [ 94  67 136]]

 [[113 104 211]
  [177 151  71]
  [ 11   9  85]
  [239  94 100]]

 [[156  33 131]
  [120 117  29]
  [ 29 245  49]
  [239 213 241]]

 [[  8  36  64]
  [229 235 165]
  [178 101 204]
  [ 70  19 241]]]


In [19]:
# 5A 

def identity(I):
    I2 = I.copy()
    return I2

print("Identity \n", identity(I))

# 5B

def downscaling(I):
    scale_factor = int(input("Scale by: "))
    new_h = int(I.shape[0] / scale_factor)
    new_w = int(I.shape[1] / scale_factor)
    I2 = np.zeros((new_h, new_w, I.shape[2]), dtype = I.dtype)
    for i in range(new_h):
        for j in range(new_w):
            I2[i,j] = I[int(i*scale_factor), int(j*scale_factor)]
    return I2

def upscaling(I):
    scale_factor = int(input("Scale by: "))
    new_h = int(I.shape[0] * scale_factor)
    new_w = int(I.shape[1] * scale_factor)
    I2 = np.zeros((new_h, new_w, I.shape[2]), dtype = I.dtype)
    for i in range(new_h):
        for j in range(new_w):
            I2[i,j] = I[int(i / scale_factor), int(j / scale_factor)]
    return I2
    
print("\nDownscaling \n", downscaling(I))
print("\nUpscaling \n", upscaling(I))

Identity 
 [[[153  56 138]
  [206  73  61]
  [162 167 134]
  [ 94  67 136]]

 [[113 104 211]
  [177 151  71]
  [ 11   9  85]
  [239  94 100]]

 [[156  33 131]
  [120 117  29]
  [ 29 245  49]
  [239 213 241]]

 [[  8  36  64]
  [229 235 165]
  [178 101 204]
  [ 70  19 241]]]
Scale by: 2

Downscaling 
 [[[153  56 138]
  [162 167 134]]

 [[156  33 131]
  [ 29 245  49]]]
Scale by: 2

Upscaling 
 [[[153  56 138]
  [153  56 138]
  [206  73  61]
  [206  73  61]
  [162 167 134]
  [162 167 134]
  [ 94  67 136]
  [ 94  67 136]]

 [[153  56 138]
  [153  56 138]
  [206  73  61]
  [206  73  61]
  [162 167 134]
  [162 167 134]
  [ 94  67 136]
  [ 94  67 136]]

 [[113 104 211]
  [113 104 211]
  [177 151  71]
  [177 151  71]
  [ 11   9  85]
  [ 11   9  85]
  [239  94 100]
  [239  94 100]]

 [[113 104 211]
  [113 104 211]
  [177 151  71]
  [177 151  71]
  [ 11   9  85]
  [ 11   9  85]
  [239  94 100]
  [239  94 100]]

 [[156  33 131]
  [156  33 131]
  [120 117  29]
  [120 117  29]
  [ 29 245  49]
  [ 2

In [28]:
# 5C

def rotation(I):
    angle = int(input("Angle: "))
    theta = mt.radians(angle)
    cos_theta = mt.cos(theta)
    sin_theta = mt.sin(theta)
    cx = I.shape[0] // 2 # centro x
    cy = I.shape[1] // 2 # centro y
    I2 = np.zeros((I.shape[0], I.shape[1], I.shape[2]), dtype = I.dtype)
    for i in range(I2.shape[0]):
        for j in range(I2.shape[1]):
            x = i - cx
            y = j - cy
            new_x = int(round(x*cos_theta - y*sin_theta))
            new_y = int(round(x*sin_theta + y*cos_theta))
            # Replication
            new_x = int(round(new_x)) 
            new_y = int(round(new_y))
            if 0 <= new_x <= I2.shape[0] and 0 <= new_y <= I2.shape[1]:
                I2[i,j] = I[new_x, new_y]
    return I2

print("\nRotation \n", rotation(I))

Angle: 120

Rotation 
 [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[156  33 131]
  [113 104 211]
  [  0   0   0]
  [  0   0   0]]

 [[120 117  29]
  [113 104 211]
  [153  56 138]
  [  0   0   0]]

 [[ 11   9  85]
  [206  73  61]
  [206  73  61]
  [  0   0   0]]]


In [33]:
# 5D

def translation(I):
    dx = int(input("Move the x by: "))
    dy = int(input("Move the y by: "))
    I2 = np.zeros((I.shape[0], I.shape[1], I.shape[2]), dtype = I.dtype)
    for i in range(I2.shape[0]):
        for j in range(I2.shape[1]):
            x = i - dx
            y = j - dy
            # Replication
            new_x = int(round(x))
            new_y = int(round(y))
            if 0 <= new_x <= I2.shape[0] and 0 <= new_y <= I2.shape[1]:
                I2[i,j] = I[x,y]
    return I2

print("\nTranslation \n", translation(I))

Move the x by: 1
Move the y by: 1

Translation 
 [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [153  56 138]
  [206  73  61]
  [162 167 134]]

 [[  0   0   0]
  [113 104 211]
  [177 151  71]
  [ 11   9  85]]

 [[  0   0   0]
  [156  33 131]
  [120 117  29]
  [ 29 245  49]]]


In [ ]:
"""
6. Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator (using 
the input function) containing randomly generated numbers in the range [0, 255] 
a. 
Create the negative matrix defined as I[x,y] = 255 - I[x,y]
"""

In [34]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[ 90 250 177]
  [ 76  31 123]
  [102 144  31]
  [189 226 190]]

 [[181  14  67]
  [ 42 197 253]
  [153  91  26]
  [223   4  12]]

 [[ 45  70 225]
  [225  65 120]
  [250  40  45]
  [234  32 111]]

 [[239 252 115]
  [174  81 172]
  [254 200 118]
  [217 179 124]]]


In [39]:
# 6A

def negative(I):
    I2 = I.copy()
    for i in range(I2.shape[0]):
        for j in range(I2.shape[1]):
            for k in range(I2.shape[2]):
                I2[i][j][k] = 255 - I[i][j][k]
    return I2

"""
def negative(I):
    I2 = 255 - I
    return I2
"""

print("\nNegative \n", negative(I))


Negative 
 [[[165   5  78]
  [179 224 132]
  [153 111 224]
  [ 66  29  65]]

 [[ 74 241 188]
  [213  58   2]
  [102 164 229]
  [ 32 251 243]]

 [[210 185  30]
  [ 30 190 135]
  [  5 215 210]
  [ 21 223 144]]

 [[ 16   3 140]
  [ 81 174  83]
  [  1  55 137]
  [ 38  76 131]]]


In [ ]:
"""
7. Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator (using 
the input function) containing randomly generated numbers in the range [0, 255] 
a. Implement the Decimation function considering the average of pixels 
b. Implement the Decimation function considering the minimum value of pixels
c. Implement the Decimation function considering the maximum pixel value
"""

In [40]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[108 132 233]
  [  9  62 210]
  [163 109 166]
  [ 61   0 121]]

 [[  0 238  77]
  [251 155 233]
  [166  70  36]
  [116 214  48]]

 [[ 54  90  80]
  [ 16 180  63]
  [151  50 210]
  [  5  71 233]]

 [[ 11 158 241]
  [ 48   2 193]
  [ 82  57 206]
  [169 178  39]]]


In [46]:
# 7A

def decimation_avg(I):
    I2 = np.zeros((I.shape[0] // 2, I.shape[1] // 2, I.shape[2] // 2), dtype = I.dtype)
    for i in range(I2.shape[0]):
        for j in range(I2.shape[1]):
            block = I[i*2:(i+1)*2, j*2:(j+1)*2]
            I2[i,j] = np.mean(block)
    return I2

print("Decimation average \n", decimation_avg(I))

Decimation average 
 [[[142]
  [105]]

 [[ 94]
  [120]]]


In [47]:
# 7B

def decimation_min(I):
    I2 = np.zeros((I.shape[0] // 2, I.shape[1] // 2, I.shape[2] // 2), dtype = I.dtype)
    for i in range(I2.shape[0]):
        for j in range(I2.shape[1]):
            block = I[i*2:(i+1)*2, j*2:(j+1)*2]
            I2[i,j] = np.min(block)
    return I2

print("Decimation minimum \n", decimation_min(I))

Decimation minimum 
 [[[0]
  [0]]

 [[2]
  [5]]]


In [48]:
# 7C

def decimation_max(I):
    I2 = np.zeros((I.shape[0] // 2, I.shape[1] // 2, I.shape[2] // 2), dtype = I.dtype)
    for i in range(I2.shape[0]):
        for j in range(I2.shape[1]):
            block = I[i*2:(i+1)*2, j*2:(j+1)*2]
            I2[i,j] = np.max(block)
    return I2

print("Decimation maximum \n", decimation_max(I))

Decimation maximum 
 [[[251]
  [214]]

 [[241]
  [233]]]


In [ ]:
"""
8. Write a Python program that takes as input a numpy N*M matrix and applies the Zoom-In 
operation (kx, with k entered by the user via the input function) and, subsequently, performs 
replication-type interpolation. Specifically: 
▪ Define the Zoom-In function (def Zoom-In(x)). 
▪ Define the Interpolation function (def Interp(x)) 
▪ Create the numpy array m of random values between 0 and 255 of size N*M 
▪ Execute the Zoom-In function (mz = Zoom-In(m)) 
▪ Execute the Interp function (mI = Interp(mz)) 
▪ Print the result (print(mI))
"""

In [5]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[ 86 162 158]
  [ 39 155 156]
  [180 104  93]
  [  6  19  73]]

 [[187 236  52]
  [106 203   0]
  [239 149 210]
  [179 113  63]]

 [[124 169   0]
  [ 44 163 247]
  [231  94  31]
  [206  82 198]]

 [[177   1  35]
  [ 35  29 244]
  [170 249  72]
  [117 160 178]]]


In [18]:
# 8

def zoom_in(I, k):
    I2 = np.zeros((I.shape[0]*k, I.shape[1]*k, I.shape[2]), dtype = I.dtype)
    return I2

def interp(I, k, zoomed_I):
    for i in range(I.shape[0]):
        for j in range(I.shape[1]):
            zoomed_I[i*k:(i+1)*k, j*k:(j+1)*k] = I[i,j]
    return zoomed_I
 
k = 2
mz = zoom_in(I, k)
mi = interp(I, k, zoomed_I)

print("Final result \n", mi)

Final result 
 [[[ 86 162 158]
  [ 86 162 158]
  [ 39 155 156]
  [ 39 155 156]
  [180 104  93]
  [180 104  93]
  [  6  19  73]
  [  6  19  73]]

 [[ 86 162 158]
  [ 86 162 158]
  [ 39 155 156]
  [ 39 155 156]
  [180 104  93]
  [180 104  93]
  [  6  19  73]
  [  6  19  73]]

 [[187 236  52]
  [187 236  52]
  [106 203   0]
  [106 203   0]
  [239 149 210]
  [239 149 210]
  [179 113  63]
  [179 113  63]]

 [[187 236  52]
  [187 236  52]
  [106 203   0]
  [106 203   0]
  [239 149 210]
  [239 149 210]
  [179 113  63]
  [179 113  63]]

 [[124 169   0]
  [124 169   0]
  [ 44 163 247]
  [ 44 163 247]
  [231  94  31]
  [231  94  31]
  [206  82 198]
  [206  82 198]]

 [[124 169   0]
  [124 169   0]
  [ 44 163 247]
  [ 44 163 247]
  [231  94  31]
  [231  94  31]
  [206  82 198]
  [206  82 198]]

 [[177   1  35]
  [177   1  35]
  [ 35  29 244]
  [ 35  29 244]
  [170 249  72]
  [170 249  72]
  [117 160 178]
  [117 160 178]]

 [[177   1  35]
  [177   1  35]
  [ 35  29 244]
  [ 35  29 244]
  [170 249 

In [ ]:
"""
9. Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator 
(using the input function) containing randomly generated numbers in the range [0, 255]. 
a. Create the bit-plane representation (Note that the image is 3-channel, so the bit planes 
will be 24) 
b. Randomly swap the bit planes.  
c. Re-create the 3-channel representation and display the result
"""

In [4]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[126 245 102]
  [180 217  95]
  [221 167  75]
  [105 167 230]]

 [[215 159 129]
  [227 149 219]
  [ 44  90  75]
  [188 152 211]]

 [[134 179 212]
  [235  52 146]
  [198  61 150]
  [246 195  19]]

 [[153 126 197]
  [211 111 230]
  [ 14 130 236]
  [254 228 125]]]


In [5]:
# 9A

def bit_plane(I):
    bit_planes = []
    for bit in range(8):
        for channel in range(I.shape[2]):
            bit_planes.append((I[:, :, channel] >> bit) & 1) # Estrazione del bit 'bit' del canale 'channel'
    bit_planes_arr = np.array(bit_planes)
    return bit_planes_arr

BP = bit_plane(I)
print(BP)

[[[0 0 1 1]
  [1 1 0 0]
  [0 1 0 0]
  [1 1 0 0]]

 [[1 1 1 1]
  [1 1 0 0]
  [1 0 1 1]
  [0 1 0 0]]

 [[0 1 1 0]
  [1 1 1 1]
  [0 0 0 1]
  [1 0 0 1]]

 [[1 0 0 0]
  [1 1 0 0]
  [1 1 1 1]
  [0 1 1 1]]

 [[0 0 1 1]
  [1 0 1 0]
  [1 0 0 1]
  [1 1 1 0]]

 [[1 1 1 1]
  [0 1 1 1]
  [0 1 1 1]
  [0 1 0 0]]

 [[1 1 1 0]
  [1 0 1 1]
  [1 0 1 1]
  [0 0 1 1]]

 [[1 0 1 1]
  [1 1 0 0]
  [0 1 1 0]
  [1 1 0 1]]

 [[1 1 0 1]
  [0 0 0 0]
  [1 0 1 0]
  [1 1 1 1]]

 [[1 0 1 1]
  [0 0 1 1]
  [0 1 0 0]
  [1 0 1 1]]

 [[0 1 0 0]
  [1 0 1 1]
  [0 0 1 0]
  [1 1 0 0]]

 [[0 1 1 0]
  [0 1 1 0]
  [0 0 0 0]
  [0 0 1 1]]

 [[1 1 1 0]
  [1 0 0 1]
  [0 0 0 1]
  [1 1 0 1]]

 [[1 1 0 0]
  [1 1 1 1]
  [1 1 1 0]
  [1 0 0 0]]

 [[0 1 0 0]
  [0 1 0 1]
  [1 1 1 1]
  [0 0 0 1]]

 [[1 1 0 1]
  [0 1 1 1]
  [0 1 0 1]
  [0 0 0 1]]

 [[1 0 1 1]
  [0 0 0 0]
  [1 1 1 0]
  [1 1 0 1]]

 [[1 0 0 1]
  [0 0 0 0]
  [0 0 0 0]
  [0 1 1 1]]

 [[1 0 1 1]
  [1 1 0 0]
  [0 1 1 1]
  [0 1 0 1]]

 [[1 1 0 0]
  [0 0 1 0]
  [0 0 0 1]
  [1 1 0 1]]



In [11]:
# 9B

def swap_bitplanes(BP): 
    swapped_BP = BP.copy()
    for row in range(0, BP.shape[0], 2):
        swapped_BP[row] = BP[row + 1]
        swapped_BP[row + 1] = BP[row]
    return swapped_BP

SW_BP = swap_bitplanes(BP)
print(SW_BP)

[[[0 0 1 0]
  [1 1 1 1]
  [1 0 1 1]
  [0 0 0 0]]

 [[0 1 1 1]
  [0 0 0 0]
  [0 1 1 1]
  [0 0 1 1]]

 [[0 0 1 1]
  [0 1 1 1]
  [0 1 1 1]
  [1 1 1 0]]

 [[1 1 1 1]
  [1 0 0 0]
  [1 1 0 1]
  [0 1 1 1]]

 [[1 1 1 1]
  [0 1 0 1]
  [0 1 1 0]
  [0 0 0 1]]

 [[0 0 0 1]
  [1 0 1 0]
  [1 0 0 1]
  [1 1 1 1]]

 [[1 1 1 0]
  [0 1 1 0]
  [0 1 1 1]
  [0 1 1 1]]

 [[0 0 1 0]
  [0 1 1 0]
  [1 1 0 0]
  [0 1 0 1]]

 [[0 1 1 0]
  [1 1 1 1]
  [0 1 1 1]
  [0 0 0 0]]

 [[1 0 1 0]
  [1 1 0 1]
  [1 1 0 1]
  [0 1 0 1]]

 [[0 1 0 1]
  [1 1 0 1]
  [0 0 0 0]
  [1 1 1 1]]

 [[0 0 1 0]
  [0 0 1 0]
  [0 1 0 0]
  [0 1 0 1]]

 [[0 0 0 1]
  [1 1 1 1]
  [1 0 1 0]
  [1 1 1 0]]

 [[0 0 1 1]
  [0 0 1 1]
  [1 1 0 1]
  [1 0 1 0]]

 [[0 1 1 1]
  [0 1 1 0]
  [0 0 1 0]
  [0 1 1 0]]

 [[1 1 1 1]
  [1 0 1 1]
  [1 0 0 0]
  [1 0 0 1]]

 [[0 1 0 0]
  [0 0 0 1]
  [1 1 0 1]
  [0 0 0 1]]

 [[0 1 1 1]
  [0 0 0 1]
  [1 1 1 1]
  [1 1 0 1]]

 [[1 1 1 0]
  [1 0 1 1]
  [0 1 0 0]
  [0 1 1 0]]

 [[0 1 0 1]
  [1 1 1 1]
  [0 1 1 0]
  [0 1 1 1]]



In [ ]:
"""
10. Creates a numpy-array of integers of size NxMx3, with N chosen dynamically by the operator 
(using the input function) containing randomly generated numbers in the range [0, 255] 
a, b, c. Obtain the Bayer Pattern considering the following Patterns: (see images)
d. Create the RGB representation from P1 by bilinear interpolation. 
e. Create the RGB representation from P2 by bilinear interpolation. 
f. Create the RGB representation from P3 using bilinear interpolation 
g. Compare the representations obtained with input I by means of MSE and PSNR 
metrics. 
h. Repeat steps d) to g) considering replication and bicubic interpolation.
"""

In [14]:
I = arr_creation2()
print(I)

Rows: 4
Columns: 4
[[[ 44 120  33]
  [  0 211 225]
  [115  33 195]
  [217 112 247]]

 [[ 58  16 220]
  [ 59 137 231]
  [ 70 230   4]
  [151 189  34]]

 [[241 200 174]
  [222 138 207]
  [ 25 211  19]
  [240 158  93]]

 [[149  26  90]
  [226 169 101]
  [ 59   6 181]
  [ 25 167 233]]]


In [15]:
# 10A, 10B, 10C

def bayer_1(I): # PATTERN GR-BG
    P1 = np.zeros((I.shape), dtype = I.dtype)
    for i in range(I.shape[0]):
        for j in range(I.shape[1]):
            if i % 2 == 0: # riga pari
                if j % 2 == 0: # riga pari, colonna pari = canale verde
                    P1[i, j, 1] = I[i, j, 1] 
                else: # riga pari, colonna dispari = canale rosso
                    P1[i, j, 0] = I[i, j, 0]
            else: # riga dispari
                if j % 2 == 0: # riga dispari, colonna pari = canale blu
                    P1[i, j, 2] = I[i, j, 2]
                else: # riga dispari, colonna dispari = canale verde
                    P1[i, j, 1] = I[i, j, 1]
    return P1

def bayer_2(I): # PATTERN GR-GB
    P2 = np.zeros((I.shape), dtype = I.dtype)
    for i in range(I.shape[0]):
        for j in range(I.shape[1]):
            if i % 2 == 0: # riga pari
                if j % 2 == 0: # riga pari, colonna pari = canale verde
                    P2[i, j, 1] = I[i, j, 1]
                else: # riga pari, colonna dispari = canale rosso
                    P2[i, j, 0] = I[i, j, 0]
            else: # riga dispari
                if j % 2 == 0: # riga dispari, colonna pari = canale verde
                    P2[i, j, 1] = I[i, j, 1]
                else: # riga dispari, colonna dispari = canale blu
                    P2[i, j, 2] = I[i, j, 2]
    return P2

def bayer_3(I): # PATTERN GR-GB-RG-GB
    P3 = np.zeros((I.shape), dtype = I.dtype)
    for i in range(I.shape[0]):
        for j in range(I.shape[1]):
            if i % 4 == 0: # riga 1 (GR)
                if j % 2 == 0: # riga 1, colonna pari = canale verde
                    P3[i, j, 1] = I[i, j, 1]
                else: # riga 1, colonna dispari = canale rosso 
                    P3[i, j, 0] = I[i, j, 0]
            elif i % 4 == 1: # riga 2 (GB)
                if j % 2 == 0: # riga 2, colonna pari = canale verde
                    P3[i, j, 1] = I[i, j, 1]
                else: # riga 2, colonna dispari = canale blu
                    P3[i, j, 2] = I[i, j, 2]
            elif i % 4 == 2: # riga 3 (RG)
                if j % 2 == 0: # riga 3, colonna pari = canale rosso
                    P3[i, j, 0] = I[i, j, 0]
                else: # riga 3, colonna dispari = canale verde
                    P3[i, j, 1] = I[i, j, 1]
            else: # riga 4 (BG)
                if j % 2 == 0: # riga 4, colonna pari = canale verde
                    P3[i, j, 2] = I[i, j, 2]
                else: # riga 4, colonna dispari = canale blu
                    P3[i, j, 1] = I[i, j, 1]
    return P3

print("Pattern 1 \n", bayer_1(I))
print("\nPattern 2 \n", bayer_2(I))
print("\nPattern 3 \n", bayer_3(I))

Pattern 1 
 [[[  0 120   0]
  [  0   0   0]
  [  0  33   0]
  [217   0   0]]

 [[  0   0 220]
  [  0 137   0]
  [  0   0   4]
  [  0 189   0]]

 [[  0 200   0]
  [222   0   0]
  [  0 211   0]
  [240   0   0]]

 [[  0   0  90]
  [  0 169   0]
  [  0   0 181]
  [  0 167   0]]]

Pattern 2 
 [[[  0 120   0]
  [  0   0   0]
  [  0  33   0]
  [217   0   0]]

 [[  0  16   0]
  [  0   0 231]
  [  0 230   0]
  [  0   0  34]]

 [[  0 200   0]
  [222   0   0]
  [  0 211   0]
  [240   0   0]]

 [[  0  26   0]
  [  0   0 101]
  [  0   6   0]
  [  0   0 233]]]

Pattern 3 
 [[[  0 120   0]
  [  0   0   0]
  [  0  33   0]
  [217   0   0]]

 [[  0  16   0]
  [  0   0 231]
  [  0 230   0]
  [  0   0  34]]

 [[241   0   0]
  [  0 138   0]
  [ 25   0   0]
  [  0 158   0]]

 [[  0   0  90]
  [  0 169   0]
  [  0   0 181]
  [  0 167   0]]]


In [16]:
P1 = bayer_1(I)
P2 = bayer_2(I)
P3 = bayer_3(I)

In [24]:
# 10D, 10E, 10F (replication)

# Per mantenerci nei bordi, verifichiamo sempre che:
# 0 <= i < I.shape[0]
# 0 <= j < I.shape[1]

def rep_bayer_1(P1):
    repP1 = P1.copy()
    for i in range(P1.shape[0]):
        for j in range(P1.shape[1]):
            for c in range(P1.shape[2]):
                if c == 0: # canale rosso
                    if j - 1 >= 0: 
                        repP1[i, j-1, c] = P1[i, j, c] # interpolazione canale rosso
                    if i + 1 < P1.shape[0] and j - 1 >= 0:
                        repP1[i+1, j-1, c] = P1[i, j, c]
                    if i + 1 < P1.shape[0]:
                        repP1[i+1, j, c] = P1[i, j, c] 
                elif c == 1 and i % 2 == 0: # canale verde, riga pari
                    if j + 1 < P1.shape[1]:
                        repP1[i, j+1, c] = P1[i, j, c] 
                elif c == 1 and i % 2 != 0: # canale verde, riga dispari
                    if j - 1 >= 0:
                        repP1[i, j-1, c] = P1[i, j, c]
                elif c == 2: # canale blu
                    if i - 1 >= 0:
                        repP1[i-1, j, c] = P1[i, j, c]
                    if i - 1 >= 0 and j + 1 < P1.shape[1]:
                        repP1[i-1, j+1, c] = P1[i, j, c]
                    if j + 1 < P1.shape[1]:
                        repP1[i, j+1, c] = P1[i, j, c]
    return repP1

def rep_bayer_2(P2):
    repP2 = P2.copy()
    for i in range(P2.shape[0]):
        for j in range(P2.shape[1]):
            for c in range(P2.shape[2]):
                if c == 0: # canale rosso
                    if j - 1 >= 0:
                        repP2[i, j-1, c] = P2[i, j, c]
                    if j + 1 < P2.shape[1]:
                        repP2[i, j+1, c] = P2[i, j, c]
                    if i + 1 < P2.shape[0]:
                        repP2[i+1, j, c] = P2[i, j, c]
                elif c == 1: # canale verde
                    if j + 1 < P2.shape[1]:
                        repP2[i, j+1, c] = P2[i, j, c]
                elif c == 2: # canale blu
                    if j - 1 >= 0:
                        repP2[i, j-1, c] = P2[i, j, c]
                    if j + 1 < P2.shape[1]:
                        repP2[i, j+1, c] = P2[i, j, c]
                    if i - 1 >= 0:
                        repP2[i - 1, j, c] = P2[i, j, c]
    return repP2

def rep_bayer_3(P3):
    repP3 = P3.copy()
    for i in range(P3.shape[0]):
        for j in range(P3.shape[1]):
            for c in range(P3.shape[2]):
                if c == 0 and j % 2 != 0: # canale rosso, colonne dispari
                    if j - 1 >= 0:
                        repP3[i, j-1, c] = P3[i, j, c]
                    if j + 1 < P3.shape[1]:
                        repP3[i, j+1, c] = P3[i, j, c]
                    if i + 1 < P3.shape[0]:
                        repP3[i+1, j, c] = P3[i, j, c]
                elif c == 0 and j % 2 == 0: # canale rosso, colonne pari
                    if j + 1 < P3.shape[1]:
                        repP3[i, j+1, c] = P3[i, j, c]
                    if i + 1 < P3.shape[0]:
                        repP3[i+1, j, c] = P3[i, j, c]
                elif c == 1:
                    if i % 4 == 0 or i % 4 == 1: # canale verde, righe 1 e 2
                        if j + 1 < P3.shape[1]:
                            repP3[i, j+1, c] = P3[i, j, c]
                    else: # canale verde, righe 3 e 4
                        if j - 1 >= 0:
                            repP3[i, j-1, c] = P3[i, j, c]
                        elif j + 1 < P3.shape[1]:
                            repP3[i, j+1, c] = P3[i, j, c]
                elif c == 2:
                    if j % 2 == 0: # canale blu, colonna pari
                        if i - 1 >= 0:
                            repP3[i-1, j, c] = P3[i, j, c]
                        elif i + 1 < P3.shape[0]:
                            repP3[i+1, j, c] = P3[i, j, c]
                        elif j + 1 < P3.shape[1]:
                            repP3[i, j+1, c] = P3[i, j, c]
                    else: # canale blu, colonna dispari
                        if i - 1 >= 0:
                            repP3[i-1, j, c] = P3[i, j, c]
                        elif i + 1 < P3.shape[0]:
                            repP3[i+1, j, c] = P3[i, j, c]
                        elif j - 1 >= 0:
                            repP3[i, j-1, c] = P3[i, j, c]
                        elif j + 1 < P3.shape[1]:
                            repP3[i, j+1, c] = P3[i, j, c]
    return repP3

                        
print("Replication Pattern 1\n", rep_bayer_1(P1))
print("\nReplication Pattern 2\n", rep_bayer_2(P2))
print("\nReplication Pattern 3\n", rep_bayer_3(P3))

repP1 = rep_bayer_1(P1)
repP2 = rep_bayer_2(P2)
repP3 = rep_bayer_3(P3)

# 10G

def metrics_rep(P1, repP1, P2, repP2, P3, repP3):
    MN_1 = P1.size
    MN_2 = P2.size
    MN_3 = P3.size
    
    MSE_1 = np.sum((repP1 - P1)**2) / MN_1
    if MSE_1 != 0:
        PSNR_1 = -10 * mt.log10(MSE_1 / np.max(P1))
    else:
        PSNR_1 = float('inf')
        
    MSE_2 = np.sum((repP2 - P2)**2) / MN_2
    if MSE_2 != 0:
        PSNR_2 = -10 * mt.log10(MSE_2 / np.max(P2))
    else:
        PSNR_2 = float('inf')
        
    MSE_3 = np.sum((repP3 - P3)**2) / MN_3
    if MSE_3 != 0:
        PSNR_3 = -10 * mt.log10(MSE_3 / np.max(P3))
    else:
        PSNR_3 = float('inf')
        
    return [(MSE_1, MSE_2, MSE_3), (PSNR_1, PSNR_2, PSNR_3)]

metrics = metrics_rep(P1, repP1, P2, repP2, P3, repP3)
print("\nMSE values\n", metrics[0])
print("\nPSNR values\n", metrics[1])

Replication Pattern 1
 [[[  0 120 220]
  [  0 120   0]
  [217   0   4]
  [217  33   0]]

 [[  0 137   0]
  [  0   0   0]
  [  0 189   0]
  [217 189   0]]

 [[222 200  90]
  [  0 200   0]
  [240   0 181]
  [  0 211   0]]

 [[  0 169  90]
  [  0   0  90]
  [  0 167   0]
  [240 167 181]]]

Replication Pattern 2
 [[[  0 120   0]
  [  0 120 231]
  [217   0   0]
  [  0  33  34]]

 [[  0  16   0]
  [  0  16   0]
  [  0   0   0]
  [  0 230   0]]

 [[222 200   0]
  [  0 200 101]
  [240   0   0]
  [  0 211 233]]

 [[  0  26 101]
  [  0  26   0]
  [  0   0 233]
  [  0   6   0]]]

Replication Pattern 3
 [[[  0 120   0]
  [  0 120 231]
  [217   0   0]
  [  0  33  34]]

 [[  0  16   0]
  [  0  16   0]
  [  0   0   0]
  [  0 230   0]]

 [[  0 138  90]
  [241   0   0]
  [  0 158 181]
  [ 25 158   0]]

 [[  0 169  90]
  [  0   0   0]
  [  0 167 181]
  [  0 167   0]]]

MSE values
 (18348.979166666668, 17976.541666666668, 13170.458333333334)

PSNR values
 (-18.834006658620112, -18.744949039978742, -17.37

In [ ]:
# 10D, 10E, 10F (bilinear interpolation)

# Per mantenerci nei bordi, verifichiamo sempre che:
# 0 <= i < I.shape[0]
# 0 <= j < I.shape[1]